### PR TITLE
Added empty search result handling

### PR DESCRIPTION
**Pull request by moom**
Hi Chris,

I've added empty search results handling in the SplunkResults class. Can you please review this? Hope this address the merging issue too.

Thanks.

Felix

### CODE REVIEW

**Comment by cbrito** [comment]
Hi Felix,

Hmm... You are correct. The merge pulled in some of the diffs. The tests passed with out problems locally. Let me see if I can clean up the origin on github.

**Comment by cbrito** [comment]
Ok - I ended up fixing the spec files by hand with credit to you. I just didn't feel like figuring out how to automate it for just those two files :)

I checked everything else and they look like they picked up the changes as expected. Let me know if you spot anything odd. 

I'm going to merge 8dcaa32 differently and see if that avoids the problem in the future.

**Comment by cbrito** [comment]
@moom 

All merged. We should make sure we are in sync if you do a `git pull upstream master`

**Comment by moom** [comment]
@cbrito  Great! Appreciated! :)

**Pull request merged**
