### PR TITLE
Added a new method to get raw

### PR DESCRIPTION
**Pull request by moom**
Hi Chris,

I've added a new method to get raw, would please consider building this into the ruby gem? Thanks.

Cheers,
Felix

### CODE REVIEW

**Comment by moom** [comment]
Hi Chris,

I've updated the test and the version file. Thanks for considering. 

Cheers,
Felix

**Comment by cbrito** [comment]
Hi @moom - I just merged 6ff37cb and 503c7d3 into master. Thanks for those.

90a69bd breaks testing. You overrode the environment variables by assigning them in the file. I left some comments in the commit around why.

Let me know if you want to fix, otherwise I'll cherrypick around them.

**Comment by moom** [comment]
Hi Chris,

Thanks for accepting the pull request. 

I used 'debugger' to debug the code, and I should've removed that line before commit. Sorry about that. I'll definitely fix the specs. And I'll add empty search result handling in SplunkResults later. 

Cheers,
Felix

**Comment by cbrito** [comment]
Awesome! I just merged 3225437 into master.

**Pull request closed without merging**
